SELECT
  G.GROUP_ID AS GROUP_ID,
  G.GROUP_NAME AS GROUP_NAME,
  COUNT(*) AS COUNT
FROM EMPLOYEE E
INNER JOIN GROUP_INFO G ON E.GROUP_ID = G.GROUP_ID
WHERE G.GROUP_ID IN /*groupIdList*/(1, 2)
GROUP BY G.GROUP_ID, G.GROUP_NAME

